In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import time
import regex

from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"G:\Datasets\Edge-IIoTset dataset\Selected dataset for ML and DL\DNN-EdgeIIoT-dataset.csv", low_memory=False)

In [3]:
pd.set_option("display.max.rows", None)
pd.set_option('display.max_columns', None)

In [4]:
df.dtypes

frame.time                    object
ip.src_host                   object
ip.dst_host                   object
arp.dst.proto_ipv4            object
arp.opcode                   float64
arp.hw.size                  float64
arp.src.proto_ipv4            object
icmp.checksum                float64
icmp.seq_le                  float64
icmp.transmit_timestamp      float64
icmp.unused                  float64
http.file_data                object
http.content_length          float64
http.request.uri.query        object
http.request.method           object
http.referer                  object
http.request.full_uri         object
http.request.version          object
http.response                float64
http.tls_port                float64
tcp.ack                      float64
tcp.ack_raw                  float64
tcp.checksum                 float64
tcp.connection.fin           float64
tcp.connection.rst           float64
tcp.connection.syn           float64
tcp.connection.synack        float64
t

In [5]:
df['Attack_type'].value_counts()

Normal                   1615643
DDoS_UDP                  121568
DDoS_ICMP                 116436
SQL_injection              51203
Password                   50153
Vulnerability_scanner      50110
DDoS_TCP                   50062
DDoS_HTTP                  49911
Uploading                  37634
Backdoor                   24862
Port_Scanning              22564
XSS                        15915
Ransomware                 10925
MITM                        1214
Fingerprinting              1001
Name: Attack_type, dtype: int64

In [9]:
df['Attack_type'] = df['Attack_type'].str.replace('DDoS_UDP','ddos')
df['Attack_type'] = df['Attack_type'].str.replace('DDoS_ICMP','ddos')
df['Attack_type'] = df['Attack_type'].str.replace('DDoS_TCP','ddos')
df['Attack_type'] = df['Attack_type'].str.replace('DDoS_HTTP','ddos')

In [10]:
df['Attack_type'] = df['Attack_type'].str.replace('XSS','injection')
df['Attack_type'] = df['Attack_type'].str.replace('SQL_injection','injection')
df['Attack_type'] = df['Attack_type'].str.replace('Uploading','injection')

In [11]:
df['Attack_type'] = df['Attack_type'].str.replace('MITM','mitm')

In [12]:
df['Attack_type'] = df['Attack_type'].str.replace('Password','malware')
df['Attack_type'] = df['Attack_type'].str.replace('Backdoor','malware')
df['Attack_type'] = df['Attack_type'].str.replace('Ransomware','malware')

In [13]:
df['Attack_type'] = df['Attack_type'].str.replace('Port_Scanning','scanning')
df['Attack_type'] = df['Attack_type'].str.replace('Fingerprinting','scanning')
df['Attack_type'] = df['Attack_type'].str.replace('Vulnerability_scanner','scanning')

In [14]:
X = df.drop(columns=['Attack_type','Attack_label'])
y = df['Attack_type']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,stratify=y)

In [15]:
y_train.value_counts()

Normal       1292514
ddos          270381
injection      83802
malware        68752
scanning       58940
mitm             971
Name: Attack_type, dtype: int64

In [16]:
y_test.value_counts()

Normal       323129
ddos          67596
injection     20950
malware       17188
scanning      14735
mitm            243
Name: Attack_type, dtype: int64

In [12]:
df['Attack_type'].value_counts()

Normal       1615643
ddos          337977
injection     104752
malware        85940
scanning       73675
mitm            1214
Name: Attack_type, dtype: int64

In [13]:
df=df.sample(frac = 1)

In [14]:
label_encoder = LabelEncoder()

In [15]:
df['Attack_type'] = label_encoder.fit_transform(df['Attack_type'])
df['Attack_type'] = df['Attack_type'].astype(int)

In [16]:
for i in df.columns:
    if(df[i].dtypes == object):
        df[i] = label_encoder.fit_transform(df[i])
        df[i] = df[i].astype(float)
    print(df[i].dtypes)

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
int64
int32


In [17]:
X = df.drop(columns=['Attack_type','Attack_label'])
y = df['Attack_label']
y1 = df['Attack_type']

In [18]:
X.dtypes

frame.time                   float64
ip.src_host                  float64
ip.dst_host                  float64
arp.dst.proto_ipv4           float64
arp.opcode                   float64
arp.hw.size                  float64
arp.src.proto_ipv4           float64
icmp.checksum                float64
icmp.seq_le                  float64
icmp.transmit_timestamp      float64
icmp.unused                  float64
http.file_data               float64
http.content_length          float64
http.request.uri.query       float64
http.request.method          float64
http.referer                 float64
http.request.full_uri        float64
http.request.version         float64
http.response                float64
http.tls_port                float64
tcp.ack                      float64
tcp.ack_raw                  float64
tcp.checksum                 float64
tcp.connection.fin           float64
tcp.connection.rst           float64
tcp.connection.syn           float64
tcp.connection.synack        float64
t

In [19]:
X.shape

(2219201, 61)

In [20]:
X.head()

frame.time  ip.src_host  ip.dst_host  arp.dst.proto_ipv4  arp.opcode  \
1613707      3665.0      58101.0      22987.0                 0.0         0.0   
289555     475002.0      58101.0      22987.0                 0.0         0.0   
1522787   1687825.0      58101.0      22987.0                 0.0         0.0   
1839683    843477.0      58101.0      22989.0                 0.0         0.0   
85616      143263.0      58101.0      22987.0                 0.0         0.0   

         arp.hw.size  arp.src.proto_ipv4  icmp.checksum  icmp.seq_le  \
1613707          0.0                 0.0            0.0          0.0   
289555           0.0                 0.0            0.0          0.0   
1522787          0.0                 0.0            0.0          0.0   
1839683          0.0                 0.0            0.0          0.0   
85616            0.0                 0.0            0.0          0.0   

         icmp.transmit_timestamp  icmp.unused  http.file_data  \
1613707                      0.0          0.0             2.0   
289555                       0.0          0.0             2.0   
1522787                      0.0          0.0             2.0   
1839683                      0.0          0.0             1.0   
85616                        0.0          0.0             2.0   

         http.content_length  http.request.uri.query  http.request.method  \
1613707                  0.0                    23.0                  1.0   
289555                   0.0                    23.0                  1.0   
1522787                  0.0                    23.0                  1.0   
1839683                  0.0                    23.0                  0.0   
85616                    0.0                    23.0                  1.0   

         http.referer  http.request.full_uri  http.request.version  \
1613707           2.0                    1.0                   5.0   
289555            2.0                    1.0                   5.0   
1522787           2.0                    1.0                   5.0   
1839683           2.0                    0.0                   4.0   
85616             2.0                    1.0                   5.0   

         http.response  http.tls_port  tcp.ack   tcp.ack_raw  tcp.checksum  \
1613707            0.0            0.0     14.0  3.625857e+09       38506.0   
289555             0.0            0.0      1.0  3.963160e+09       55320.0   
1522787            0.0            0.0     59.0  2.897867e+09          69.0   
1839683            0.0            0.0    261.0  8.377503e+08       15856.0   
85616              0.0            0.0      0.0  0.000000e+00       50455.0   

         tcp.connection.fin  tcp.connection.rst  tcp.connection.syn  \
1613707                 0.0                 0.0                 0.0   
289555                  0.0                 0.0                 0.0   
1522787                 0.0                 0.0                 0.0   
1839683                 0.0                 0.0                 0.0   
85616                   0.0                 1.0                 0.0   

         tcp.connection.synack  tcp.dstport  tcp.flags  tcp.flags.ack  \
1613707                    0.0      54045.0       16.0            1.0   
289555                     1.0      51596.0       18.0            1.0   
1522787                    0.0      54849.0       16.0            1.0   
1839683                    0.0      33392.0       16.0            1.0   
85616                      0.0      54180.0        4.0            0.0   

         tcp.len  tcp.options  tcp.payload  tcp.seq  tcp.srcport  udp.port  \
1613707      0.0          0.0          0.0      2.0      41169.0       0.0   
289555       0.0     203128.0          0.0      0.0       8860.0       0.0   
1522787      0.0          0.0          0.0      6.0       8860.0       0.0   
1839683      0.0     116671.0          0.0      1.0      59770.0       0.0   
85616        0.0          0.0          0.0      6.0       8860.0       0.0   

         u

In [21]:
y1.value_counts()

0    1615643
1     337977
2     104752
3      85940
5      73675
4       1214
Name: Attack_type, dtype: int64

In [ ]:
# the following attributes are already identified to be drop in DL_Data_sub_cat_multi_class_Edge_IIoTset.ipynb using feature selection method.

In [22]:
X=X.drop(columns=['icmp.transmit_timestamp','icmp.unused','http.tls_port','dns.qry.type','mqtt.msg_decoded_as','mbtcp.len','mbtcp.unit_id'])

In [23]:
#Normalization of dataset

In [24]:
X.shape

(2219201, 54)

In [25]:
X=((X-X.min())/(X.max()-X.min()))*1

In [26]:
X = np.array(X, dtype=float)

In [27]:
X = X.reshape(2219201, 54, 1)

In [28]:
X.shape

(2219201, 54, 1)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y1, test_size=0.2,stratify=y1)

In [30]:
X_train.shape

(1775360, 54, 1)

In [31]:
y_train.value_counts()

0    1292514
1     270381
2      83802
3      68752
5      58940
4        971
Name: Attack_type, dtype: int64

In [32]:
X_test.shape

(443841, 54, 1)

In [33]:
y_test.value_counts()

0    323129
1     67596
2     20950
3     17188
5     14735
4       243
Name: Attack_type, dtype: int64

In [34]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import time
import regex

from tensorflow import keras
from tensorflow.keras import layers
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM, GRU, RNN, SimpleRNN
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn import metrics
import numpy as np
import seaborn as sn
from sklearn.metrics import multilabel_confusion_matrix

from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
import keras
from keras.layers import Convolution1D, Dense, Dropout, Flatten, MaxPooling1D , AveragePooling1D

from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM, GRU
import matplotlib.pyplot as plt
from sklearn import metrics
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix

from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
import tensorflow as tf
from keras.utils.vis_utils import plot_model

from sklearn.model_selection import StratifiedKFold
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from scipy.stats import zscore
from sklearn.model_selection import KFold

In [35]:
##########
###      LSTM
##########   

In [37]:
model = Sequential()
model.add(LSTM(27, input_shape=(54, 1), return_sequences=True))
model.add(LSTM(6, activation='softmax', return_sequences=False))
model.compile(loss='sparse_categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs = 6).history

Epoch 1/6
55480/55480 [==============================] - 2094s 38ms/step - loss: 0.2297 - accuracy: 0.9094
Epoch 2/6
55480/55480 [==============================] - 2130s 38ms/step - loss: 0.0303 - accuracy: 0.9897
Epoch 3/6
55480/55480 [==============================] - 2065s 37ms/step - loss: 0.0643 - accuracy: 0.9782
Epoch 4/6
55480/55480 [==============================] - 2071s 37ms/step - loss: 0.0334 - accuracy: 0.9902
Epoch 5/6
55480/55480 [==============================] - 2068s 37ms/step - loss: 0.0149 - accuracy: 0.9955
Epoch 6/6
55480/55480 [==============================] - 2082s 38ms/step - loss: 0.0069 - accuracy: 0.9977


In [38]:
hist_df = pd.DataFrame(history) 

# and save to csv: 
hist_csv_file = 'G:/Training Results/b_LSTM.csv'
with open(hist_csv_file, mode='w') as f:
    hist_df.to_csv(f)

In [35]:
vd_preds_G = model.predict(X_test).argmax(axis=1)

print("Precision: ",precision_score(y_test,vd_preds_G,average='macro'))
print("Recall: ", recall_score(y_test,vd_preds_G,average='macro'))
print("F1-score: ", f1_score(y_test,vd_preds_G,average='macro'))
print("Accuracy: ", accuracy_score(y_test,vd_preds_G))

Precision:  0.992101471629169
Recall:  0.9957224139417092
F1-score:  0.9938391469616196
Accuracy:  0.9983079526226735


In [ ]:
#######
###    CNN MODEL
######

In [ ]:
model_CNN_D1 = Sequential()
model_CNN_D1.add(Convolution1D(27, 3, padding="same",activation="relu",input_shape = (54, 1)))
model_CNN_D1.add(MaxPooling1D(pool_size=(4)))
model_CNN_D1.add(Flatten())
model_CNN_D1.add(Dense(6, activation="softmax"))
model_CNN_D1.compile(loss='sparse_categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
history = model_CNN_D1.fit(X_train, y_train, epochs = 6).history

In [37]:
hist_df = pd.DataFrame(history) 

# and save to csv: 
hist_csv_file = 'G:/Training Results/b_CNN.csv'
with open(hist_csv_file, mode='w') as f:
    hist_df.to_csv(f)

In [38]:
vd_preds_G = model_CNN_D1.predict(X_test).argmax(axis=1)

print("Precision: ",precision_score(y_test,vd_preds_G,average='macro'))
print("Recall: ", recall_score(y_test,vd_preds_G,average='macro'))
print("F1-score: ", f1_score(y_test,vd_preds_G,average='macro'))
print("Accuracy: ", accuracy_score(y_test,vd_preds_G))

Precision:  0.9950298285188707
Recall:  0.9938667156966954
F1-score:  0.9944317290269903
Accuracy:  0.9986121155999559


In [79]:
#GRU

In [39]:
model = Sequential()
model.add(GRU(27, input_shape=(54, 1), return_sequences=True))
model.add(GRU(6, activation='softmax', return_sequences=False))
model.compile(loss='sparse_categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs = 6).history

Epoch 1/6
55480/55480 [==============================] - 1468s 26ms/step - loss: 0.1507 - accuracy: 0.9458
Epoch 2/6
55480/55480 [==============================] - 1983s 36ms/step - loss: 0.0111 - accuracy: 0.9966
Epoch 3/6
55480/55480 [==============================] - 1518s 27ms/step - loss: 0.0074 - accuracy: 0.9978
Epoch 4/6
55480/55480 [==============================] - 1124s 20ms/step - loss: 0.0056 - accuracy: 0.9982
Epoch 5/6
55480/55480 [==============================] - 1128s 20ms/step - loss: 0.0050 - accuracy: 0.9983
Epoch 6/6
55480/55480 [==============================] - 1128s 20ms/step - loss: 0.0091 - accuracy: 0.9976


In [40]:
hist_df = pd.DataFrame(history) 

# and save to csv: 
hist_csv_file = 'G:/Training Results/b_GRU.csv'
with open(hist_csv_file, mode='w') as f:
    hist_df.to_csv(f)

In [41]:
vd_preds_G = model.predict(X_test).argmax(axis=1)

print("Precision: ",precision_score(y_test,vd_preds_G,average='macro'))
print("Recall: ", recall_score(y_test,vd_preds_G,average='macro'))
print("F1-score: ", f1_score(y_test,vd_preds_G,average='macro'))
print("Accuracy: ", accuracy_score(y_test,vd_preds_G))

Precision:  0.9870199147569226
Recall:  0.988764036343003
F1-score:  0.9878704908590944
Accuracy:  0.998364279099948


In [ ]:
##############################################################################################

In [ ]:
#################################################################################################

In [80]:
X_train_b = X_train.reshape(1775360, 54)
X_test_b = X_test.reshape(443841, 54)

In [81]:
X_b = X.reshape(2219201, 54)

In [82]:
X.shape

(2219201, 54, 1)

In [83]:
# AEC ------------- here is stop

In [ ]:
Model = Sequential()
Model.add(Dense(54, activation = 'relu', input_dim = 54))
Model.add(Dense(27, activation = 'relu'))
Model.add(Dense(13, activation = 'relu'))
Model.add(Dense(13, activation = 'relu'))
Model.add(Dense(27, activation = 'relu'))
Model.add(Dense(54,  activation = 'softmax'))
Model.compile(optimizer ='adam',loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
history = Model.fit(X_train_b, y_train, epochs = 6).history

In [85]:
hist_csv_file = 'G:/Training Results/b_AEC.csv'
with open(hist_csv_file, mode='w') as f:
    hist_df.to_csv(f)

In [86]:
y_pred_L = Model.predict(X_test_b).argmax(axis=1)

print(precision_score(y_test,y_pred_L,average='macro'))
print(recall_score(y_test,y_pred_L,average='macro'))
print(f1_score(y_test,y_pred_L,average='macro'))
print(accuracy_score(y_test,y_pred_L))

0.9952113026791869
0.9981326423943943
0.9966568971372113
0.9995493881818038


In [87]:
# MLP

In [88]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(5,10), random_state=1)
mlp.fit(X_train_b,y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 10), random_state=1)

In [89]:
vd_preds_G = mlp.predict(X_test_b)
con_G=confusion_matrix(y_test, vd_preds_G)
print(con_G)
print("Precision: ",precision_score(y_test,vd_preds_G,average='macro'))
print("Recall: ", recall_score(y_test,vd_preds_G,average='macro'))
print("F1-score: ", f1_score(y_test,vd_preds_G,average='macro'))
print("Accuracy: ", accuracy_score(y_test,vd_preds_G))

[[323128      0      0      0      0      1]
 [     0  67595      0      1      0      0]
 [     0      1  20868      1      4     76]
 [     0      2      1  17047      0    138]
 [     0      0      0      0    243      0]
 [     0    165     32     46      0  14492]]
Precision:  0.9937201399333904
Recall:  0.9952288809147277
F1-score:  0.9944616445391868
Accuracy:  0.998945568345421


In [90]:
#Logistic regresion

In [91]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X_train_b,y_train)

C:\Users\PC\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [92]:
vd_preds_G = logreg.predict(X_test_b)

print("Precision: ",precision_score(y_test,vd_preds_G,average='macro'))
print("Recall: ", recall_score(y_test,vd_preds_G,average='macro'))
print("F1-score: ", f1_score(y_test,vd_preds_G,average='macro'))
print("Accuracy: ", accuracy_score(y_test,vd_preds_G))

Precision:  0.9161426207444139
Recall:  0.9111559203740596
F1-score:  0.9127812368873082
Accuracy:  0.9859093684450062


In [93]:
#NB

In [94]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train_b, y_train)

GaussianNB()

In [95]:
vd_preds_G = classifier.predict(X_test_b)

print("Precision: ",precision_score(y_test,vd_preds_G,average='macro'))
print("Recall: ", recall_score(y_test,vd_preds_G,average='macro'))
print("F1-score: ", f1_score(y_test,vd_preds_G,average='macro'))
print("Accuracy: ", accuracy_score(y_test,vd_preds_G))

Precision:  0.8767505203567388
Recall:  0.8371436384260568
F1-score:  0.8310422010126661
Accuracy:  0.9422000220799791


In [96]:
#SVM

In [97]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train_b, y_train)

SVC(kernel='linear')

In [98]:
vd_preds_G = clf.predict(X_test_b)

print("Precision: ",precision_score(y_test,vd_preds_G,average='macro'))
print("Recall: ", recall_score(y_test,vd_preds_G,average='macro'))
print("F1-score: ", f1_score(y_test,vd_preds_G,average='macro'))
print("Accuracy: ", accuracy_score(y_test,vd_preds_G))

Precision:  0.9827015176985588
Recall:  0.9855975103813752
F1-score:  0.9841140307785708
Accuracy:  0.9954488206362189
